name: KeepAlive

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  KeepAlive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup Github CLI
        # You may pin to the exact commit or the version.
        # uses: Monorepo-Actions/setup-gh-cli@8b4bea5196708d4678ca9ccdc678012095a81180
        uses: Monorepo-Actions/setup-gh-cli@v1.0.0
        with:
          # The GitHub token to authenticate GitHub CLI.
          token: ${{ secrets.token }}
          
      - name: Connect to codespace
        run: python connect.py
